spring.application.name=taskboard

spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard
spring.datasource.username=taskboard
spring.datasource.password=taskboard

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.locations=classpath:db/migration
